language: python
python:
- '3.6'
- '3.7'
install:
- pip install -r requirements.txt
script:
- echo 'running pretend tests'
before_deploy: echo 'ready?'
deploy:
  on:
    tags: true
  provider: heroku
  api_key:
    secure: caHnycH3YtyadBhJbiEI7zKg0wQ4zha+V0DhBOmQX16cv3z7YHohGuHXbJjZ/z4wo7EdtmPonRYEsJo90kPwaLkfOuql/bJmjSzgUThOuFJKfTyEpr79SPKkHZUwohuoGoMuPtjwTfmqreGtAskNH96UOiDlR5s/haq7GK3PBxWlQdQlw11+knZwo4uJi5+8AgUk5q9wown+aoDcvaCJQAfg8/t88LTYdLrxMD3RrOD1KAIJ2z/9UBZbdLghOIeB7t7o6MrQBLXYohROjEWm529ir0GPPUUvLnj52fw92PnDd0AQTqXjs2kSA9K1wLGryvgUO1A04vJBHhL9Q4f8dzFMiYJkfviOmno7WsWDgH1QounBKFIG6cjIeEl0LLyhC09NmFpIovpXktewmrDKMJDPK17tGHS++yZb7mw9gceA6pVjgPX/ahejukhKv5dpzh+QO1JI1hUdt7kPiQmRLFEhIwoBJKz8qHRsTplpDZ/13vYTi70Dg+fsjT+MQ8dxyiCrG1BSY/x8/eH1/93R2htWtZZSI0njgupNXtsAb3KlNfFDN6qSeyDi4kEOqIwNw3RbWTo6qPGKnD2ZG80yzI1vfD7UnHEKId/iPUVrvKvtYZPf4nI81DApyAUWdrA1hMFXBg5hMJGT70GYc2xY+8V8HKdyotO6SVwFSyBm1Wc=
  app: indonesia-model
after_deploy:
- echo 'after deployment'
notifications:
  email: false
