language: python
python:
- '3.6'
- '3.7'
install:
- pip install -r requirements.txt
script:
- echo 'running pretend tests'
before_deploy: echo 'ready?'
deploy:
  on:
    tags: true
  provider: heroku
  api_key:
    secure: l1H0GUFzZ2CJ3Wd0ChWhcLCwwd4xl80+4bwW2Ya0/b1bfL3rpW1uXOh06Asv3bP1VM8ccXZHTEI+3X40TaWEr8GxC96BK9UeO0ruvI+airs1LTOiQzp7B311DW9TY0id6/Mv11RaH+S8a6UEEj+vbTI1zE/P0UchDwTqFPA5QxB/tSmrR+Yp9454yNFJsGUx1/T9Davz3SgsaOB39pTJo5+Fk0bm6U/vKgE2AXDOKDdZhMbQa8S72Tbtzetx5aoQeRebdfhyv0Vzsp7jdGGDU23zXV0RwRnQ5FKZN1nGqjD33iGLPfEuMZxbnnUB97ZcV4jr+QDliURyRXP2rl9ek5AmJlBzEaLzN23PJ8tSWSVMg8eLvEniA+fJyUotp2oLUNA3t82VQjvZJAbQWtqFk1arQfeHcaS35zd55u5pvU0sZCodVTMLQzuFf8N6ByUgUQApn1FUtaw/KjxCrlHGO7RTKOMxISYTsfH8nFUvpcx4ufsONVxhXJZPD00yYCOge9f8JiK6gTljwG/SbAkB7Hrcg/X2jdN5UTuRUaA3URmFNy/XfTnteJElYIgueHyjI7ASugG0qIfFdOy+fAa7gaQ9Gjb8Wp8bQh4l61sv3o9ugcB2jPNz9HnmprSLFZdpXgBoOxggyxJYME6htIir6o8FMjSTGN7Jf0uHZ81MMHY=
  app: indonesia-model
after_deploy:
- echo 'after deployment'
notifications:
  email: false
